### PR TITLE
Improve docker build for javascript frameworks

### PR DESCRIPTION
**Pull request by mihaur**
Use node:slim base image instead of node:alpine
Use tini as docker entrypoint to properly handle signals (SIGINT/SIGHUP used by docker stop)
Run as node user instead of root

### CODE REVIEW

**Comment by mihaur** [comment]
Use node:slim base image instead of node:alpine
Use tini as docker entrypoint to properly handle signals (SIGINT/SIGHUB used by docker stop)
Run as node user instead of root

**Comment by ohler55** [comment]
Looks good but I'm away from the machine I use to run the tests. I can run the changes Sunday. All changes seems reasonable though.

**Comment by mihaur** [comment]
Sounds great. I don't expect numbers to change dramaticaly.

**Comment by ohler55** [comment]
Site has been updated with the latest. Not significant changes in results as expected. Thanks for the updates. The docker files are a bit more robust.

**Pull request merged**
